FROM --platform=linux/arm64 python:3.10-slim

WORKDIR /opt/dagster/app

RUN apt-get update && apt-get install -y nano

COPY requirements.txt /my_dagster_code/ /opt/dagster/app/

RUN pip install --upgrade pip setuptools && \
    pip install -r requirements.txt

RUN pip install watchdog

EXPOSE 4000

# Set environment variables for auto-reload
ENV DAGSTER_WATCHER_POLLING=true
ENV DAGSTER_WATCHER_POLLING_INTERVAL=10

# Start code server with basic command (environment variables will handle the reload)
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "SCRIPT16.py"]