FROM --platform=linux/arm64 python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

#RUN pip install --upgrade pip setuptools

# Add repository code

WORKDIR /opt/dagster/app

RUN apt-get update && apt-get install -y nano  # Install nano

# Copy all necessary files
#COPY definitions.py excel_config.env MM_BIL.py requirements.txt /my_dagster_code/ /opt/dagster/app/
COPY  requirements.txt /my_dagster_code/ /opt/dagster/app/

RUN pip install -r requirements.txt
RUN pip install --upgrade pip setuptools
# Run dagster gRPC server on port 4000

EXPOSE 4000

#CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "SCRIPT16.py"]