# Source code generated by Amphi for Dagster
# Date: 2025-04-16 15:15:36
# Additional dependencies: dagster, psycopg2-binary
import dagster
from dagster import op, job, Out, In, Nothing
import pandas as pd
import sqlalchemy
import psycopg2
# No environment variable components found.
import os

# Connection constants for Postgres
POSTGRES_HOST = "psqldb"
POSTGRES_PORT = "5432"
POSTGRES_DATABASE_NAME = "ecdwh"
POSTGRES_USERNAME = "bruno"
POSTGRES_PASSWORD = "bruno"
POSTGRES_SCHEMA = "public"

@op
def csvFileInputOp():
  """ csvFileInput """
  # Reading data from username.csv
  result = pd.read_csv("username.csv", sep=";").convert_dtypes()
  return result

@op
def filterOp(input_data: pd.DataFrame):
  """ filter """

  # Filter rows based on condition
  result = input_data[input_data['First name'].str.contains("ra", na=False)]

  return result

@op
def postgresOutputOp(input_data: pd.DataFrame):
  """ postgresOutput """


  # Connect to the Postgres database
  input_dataEngine = sqlalchemy.create_engine(
    f"postgresql://{POSTGRES_USERNAME}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DATABASE_NAME}"
  )


  # Rename columns based on the mapping
  input_data = input_data.rename(columns={"First name": "field_name"})

  # Only keep relevant columns
  input_data = input_data[["field_name"]]

  # Write DataFrame to Postgres
  try:
      input_data.to_sql(
          name="simple_csv",
          con=input_dataEngine,
          if_exists="append",
          index=False,
    schema=POSTGRES_SCHEMA
      )
  finally:
      input_dataEngine.dispose()

  return



@job
def dagster_pipeline():
    csvFileInputResult = csvFileInputOp()
    filterResult = filterOp(csvFileInputResult)
    postgresOutputResult = postgresOutputOp(filterResult)
